In [1]:
import pandas as pd

In [2]:
data = {"names":['Jane',"janet",'John','jacob','vishwas'],
        "age": [23, '25',None,16,15]}

In [3]:
df = pd.DataFrame(data)
df.head()

     names   age
0     Jane    23
1    janet    25
2     John  None
3    jacob    16
4  vishwas    15

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   5 non-null      object
 1   age     4 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes

In [6]:
df.describe()

       names  age
count      5    4
unique     5    4
top     Jane   23
freq       1    1

In [8]:
df['age'].astype('int')

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

In [ ]:
# data = {"names":['Jane',None],
#         "age": [None, 23]}

In [9]:
df['age'].isna().sum()

np.int64(1)

In [10]:
new_df = df.copy()
new_df['age'].fillna(0, inplace=True)

C:\Users\VishwasKSingh\AppData\Local\Temp\ipykernel_18540\852180089.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['age'].fillna(0, inplace=True)

In [11]:
new_df.head()

     names age
0     Jane  23
1    janet  25
2     John   0
3    jacob  16
4  vishwas  15